# Generated by Django 5.0.3 on 2024-12-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_first_year_fourth_year_grade_eleven_grade_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertracking',
            name='top_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careertracking',
            name='top_three',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careertracking',
            name='top_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grade_eleven',
            name='emotional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
