# Generated by Django 5.0.3 on 2024-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_careertracking_top_one_careertracking_top_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careertracking',
            name='hobbies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
