# Generated by Django 5.0.3 on 2024-12-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_careertracking_psych_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualrecordform',
            name='living_with',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='individualrecordform',
            name='parents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
