# Generated by Django 5.0.3 on 2024-12-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_routineinterview_academic_problem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careertracking',
            name='academic_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='academic_track',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='cognitive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='emotional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='medical_records',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='personality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='careertracking',
            name='tech_voc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
