# Generated by Django 5.1 on 2025-01-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
